-- MySQL Script generated by MySQL Workbench
-- Sun Sep 10 22:40:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios_Compradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios_Compradores` (
  `idcompradores` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `correo_electronico` VARCHAR(20) NOT NULL,
  `telefono` INT UNSIGNED NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `RFC` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idcompradores`),
  UNIQUE INDEX `idcompradores_UNIQUE` (`idcompradores` ASC) VISIBLE,
  UNIQUE INDEX `rfc_UNIQUE` (`RFC` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendedores` (
  `idVendedores` INT NOT NULL AUTO_INCREMENT,
  `User_vendedor` VARCHAR(20) NOT NULL,
  `password_vendedor` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `rfc` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idVendedores`),
  UNIQUE INDEX `idVendedores_UNIQUE` (`idVendedores` ASC) VISIBLE,
  UNIQUE INDEX `rfc_UNIQUE` (`rfc` ASC) VISIBLE,
  UNIQUE INDEX `UsuarioID_UNIQUE` (`User_vendedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idproductos` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `numero_serie` VARCHAR(45) NOT NULL,
  `pais_origen` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(90) NULL,
  PRIMARY KEY (`idproductos`),
  UNIQUE INDEX `idproductos_UNIQUE` (`idproductos` ASC) VISIBLE,
  UNIQUE INDEX `numero de serie_UNIQUE` (`numero_serie` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `ProductoID` INT NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `producto a categoria_idx` (`ProductoID` ASC) VISIBLE,
  CONSTRAINT `producto a categoria`
    FOREIGN KEY (`ProductoID`)
    REFERENCES `mydb`.`Productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `ProductoID` INT NOT NULL,
  `VendedorID` INT NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `Peso_unit_Kg` DECIMAL(10) NULL,
  `CategoriaID` INT NOT NULL,
  `Precio_unitario` DECIMAL(6) NOT NULL,
  PRIMARY KEY (`idInventario`),
  UNIQUE INDEX `idInventario_UNIQUE` (`idInventario` ASC) VISIBLE,
  INDEX `el vendedor_idx` (`VendedorID` ASC) VISIBLE,
  INDEX `el producto_idx` (`ProductoID` ASC) VISIBLE,
  INDEX `categoria a inventario_idx` (`CategoriaID` ASC) VISIBLE,
  CONSTRAINT `el vendedor`
    FOREIGN KEY (`VendedorID`)
    REFERENCES `mydb`.`Vendedores` (`idVendedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `el producto`
    FOREIGN KEY (`ProductoID`)
    REFERENCES `mydb`.`Productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoria a inventario`
    FOREIGN KEY (`CategoriaID`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `idcarrito` INT NOT NULL,
  `id vendedor` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `Subtotal` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`idcarrito`),
  INDEX `el vendedor_idx` (`id vendedor` ASC) VISIBLE,
  CONSTRAINT `el vendedor`
    FOREIGN KEY (`id vendedor`)
    REFERENCES `mydb`.`Vendedores` (`idVendedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Metodos de Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Metodos de Pago` (
  `idMetodos de Pago` INT NOT NULL,
  `Usuarios_Compradores_idcompradores` INT NOT NULL,
  `Tipo_Pago` VARCHAR(20) NOT NULL,
  `Detalles_numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMetodos de Pago`),
  INDEX `fk_Metodos de Pago_Usuarios_Compradores1_idx` (`Usuarios_Compradores_idcompradores` ASC) VISIBLE,
  CONSTRAINT `fk_Metodos de Pago_Usuarios_Compradores1`
    FOREIGN KEY (`Usuarios_Compradores_idcompradores`)
    REFERENCES `mydb`.`Usuarios_Compradores` (`idcompradores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Domicilios_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Domicilios_usuario` (
  `idDomicilios_usuario` INT NOT NULL,
  `Usuarios_Compradores_idcompradores` INT NOT NULL,
  `Domicilio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDomicilios_usuario`),
  INDEX `fk_Domicilios_usuario_Usuarios_Compradores1_idx` (`Usuarios_Compradores_idcompradores` ASC) VISIBLE,
  CONSTRAINT `fk_Domicilios_usuario_Usuarios_Compradores1`
    FOREIGN KEY (`Usuarios_Compradores_idcompradores`)
    REFERENCES `mydb`.`Usuarios_Compradores` (`idcompradores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transacciones` (
  `idtransacciones` INT NOT NULL,
  `id comprador` INT NOT NULL,
  `id vendedor` INT NOT NULL,
  `carrito_idcarrito` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `Monto` DECIMAL(10) NOT NULL,
  `Metodos de Pago_idMetodos de Pago` INT NOT NULL,
  `RFC_comprador` VARCHAR(20) NOT NULL,
  `RFC_vendedor` VARCHAR(20) NOT NULL,
  `Domicilios_usuario_idDomicilios_usuario` INT NOT NULL,
  PRIMARY KEY (`idtransacciones`),
  INDEX `el comprador_idx` (`id comprador` ASC) VISIBLE,
  INDEX `el vendedor_idx` (`id vendedor` ASC) VISIBLE,
  INDEX `fk_transacciones_carrito1_idx` (`carrito_idcarrito` ASC) VISIBLE,
  INDEX `fk_transacciones_Metodos de Pago1_idx` (`Metodos de Pago_idMetodos de Pago` ASC) VISIBLE,
  INDEX `RFC a transaccion_idx` (`RFC_comprador` ASC) VISIBLE,
  INDEX `RFC_vendedor a transaccion_idx` (`RFC_vendedor` ASC) VISIBLE,
  INDEX `fk_transacciones_Domicilios_usuario1_idx` (`Domicilios_usuario_idDomicilios_usuario` ASC) VISIBLE,
  CONSTRAINT `el comprador`
    FOREIGN KEY (`id comprador`)
    REFERENCES `mydb`.`Usuarios_Compradores` (`idcompradores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `el vendedor`
    FOREIGN KEY (`id vendedor`)
    REFERENCES `mydb`.`Vendedores` (`idVendedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacciones_carrito1`
    FOREIGN KEY (`carrito_idcarrito`)
    REFERENCES `mydb`.`carrito` (`idcarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacciones_Metodos de Pago1`
    FOREIGN KEY (`Metodos de Pago_idMetodos de Pago`)
    REFERENCES `mydb`.`Metodos de Pago` (`idMetodos de Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RFC a transaccion`
    FOREIGN KEY (`RFC_comprador`)
    REFERENCES `mydb`.`Usuarios_Compradores` (`RFC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RFC_vendedor a transaccion`
    FOREIGN KEY (`RFC_vendedor`)
    REFERENCES `mydb`.`Vendedores` (`rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacciones_Domicilios_usuario1`
    FOREIGN KEY (`Domicilios_usuario_idDomicilios_usuario`)
    REFERENCES `mydb`.`Domicilios_usuario` (`idDomicilios_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notificaciones` (
  `idNotificaciones` INT NOT NULL,
  `transacciones_idtransacciones` INT NOT NULL,
  `Texto_notificacion` VARCHAR(45) NOT NULL,
  `Vendedores_idVendedores` INT NOT NULL,
  `Usuarios_Compradores_idcompradores` INT NOT NULL,
  PRIMARY KEY (`idNotificaciones`),
  INDEX `fk_Notificaciones_transacciones1_idx` (`transacciones_idtransacciones` ASC) VISIBLE,
  INDEX `fk_Notificaciones_Vendedores1_idx` (`Vendedores_idVendedores` ASC) VISIBLE,
  INDEX `fk_Notificaciones_Usuarios_Compradores1_idx` (`Usuarios_Compradores_idcompradores` ASC) VISIBLE,
  CONSTRAINT `fk_Notificaciones_transacciones1`
    FOREIGN KEY (`transacciones_idtransacciones`)
    REFERENCES `mydb`.`transacciones` (`idtransacciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificaciones_Vendedores1`
    FOREIGN KEY (`Vendedores_idVendedores`)
    REFERENCES `mydb`.`Vendedores` (`idVendedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificaciones_Usuarios_Compradores1`
    FOREIGN KEY (`Usuarios_Compradores_idcompradores`)
    REFERENCES `mydb`.`Usuarios_Compradores` (`idcompradores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pre-orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pre-orden` (
  `idPre-orden` INT NOT NULL,
  `Productos_idproductos` INT NOT NULL,
  `carrito_idcarrito` INT NOT NULL,
  PRIMARY KEY (`idPre-orden`),
  INDEX `fk_Pre-orden_Productos1_idx` (`Productos_idproductos` ASC) VISIBLE,
  INDEX `fk_Pre-orden_carrito1_idx` (`carrito_idcarrito` ASC) VISIBLE,
  CONSTRAINT `fk_Pre-orden_Productos1`
    FOREIGN KEY (`Productos_idproductos`)
    REFERENCES `mydb`.`Productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pre-orden_carrito1`
    FOREIGN KEY (`carrito_idcarrito`)
    REFERENCES `mydb`.`carrito` (`idcarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reseñas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reseñas` (
  `idReseñas` INT NOT NULL,
  `Usuarios_Compradores_idcompradores` INT NOT NULL,
  `transacciones_idtransacciones` INT NOT NULL,
  `Vendedores_idVendedores` INT NOT NULL,
  `Calificacion` DECIMAL(2) NULL,
  `Reseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idReseñas`),
  INDEX `fk_Reseñas_Usuarios_Compradores1_idx` (`Usuarios_Compradores_idcompradores` ASC) VISIBLE,
  INDEX `fk_Reseñas_transacciones1_idx` (`transacciones_idtransacciones` ASC) VISIBLE,
  INDEX `fk_Reseñas_Vendedores1_idx` (`Vendedores_idVendedores` ASC) VISIBLE,
  CONSTRAINT `fk_Reseñas_Usuarios_Compradores1`
    FOREIGN KEY (`Usuarios_Compradores_idcompradores`)
    REFERENCES `mydb`.`Usuarios_Compradores` (`idcompradores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reseñas_transacciones1`
    FOREIGN KEY (`transacciones_idtransacciones`)
    REFERENCES `mydb`.`transacciones` (`idtransacciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reseñas_Vendedores1`
    FOREIGN KEY (`Vendedores_idVendedores`)
    REFERENCES `mydb`.`Vendedores` (`idVendedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
